server:
  port: 6572

# LogBack(Log4j)
logging:
  level:
    root: info

# swagger enable
springfox:
  documentation:
    swagger:
      v2:
        enabled: true
---
# --- profile local --- #
spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:15432/inn
    username: inn
    password: inn1@!2_
    driver-class-name: org.postgresql.Driver

  # hibernate optionddl-auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# banner
#banner:
#  location: banner/local-banner.txt
